# Basic Level:


### Q1.Write a Python program to print the numbers from 1 to 10 using a `for` loop.

In [1]:
def print_numbers_from_1_to_10(num: int) -> None:
    for i in range(1,num+1):
        print(i)

In [2]:
print_numbers_from_1_to_10(10)

1
2
3
4
5
6
7
8
9
10


---
- So, here we created a funnction called as `print_numbers_from_1_to_10` which are responsible for printing the number from 1 to 10
- Now execution of function is begin from the cell number 2 (which is simply a functon call)
- After that control goes inside the function and execute the task
- Using for loop we simply iterate the number from 1 t0 10 using range function
- Finally we print that number one by one on the terminal and control goes terminated
---

### Q2 Create a program that calculates the sum of all numbers in a list using a `for` loop.

In [3]:
def sum_of_numbers(nums: list[int],sum: int = 0) -> int:
    for i in nums:
        sum = sum+i
    return sum

In [4]:
print(sum_of_numbers([1,2,3,4,5]))

15


---
- As you can clearly see that this function(`sum_of_numbers`) takes two parameters first one is `nums` which holds the values of type list of integer
- and second one is `sum` which is also type of integer but this argument is known as default parameter whose value is set to zero
- Now jump into the function call because the function will run only until it is called
- Control goes inside the the function and execute the task
- Here for loop iterate the list of element one by one
- Each individual element of the list is added with the `sum` variable and assign it to in `sum` varible
- And finally we return the sum of all numbers, back to the caller and print the result.
---

### Q3 Write a program to print the characters of a string in reverse order using a `for` loop

In [5]:
def reverse(name: str) -> None:
    for i in name[::-1]:
        print(i)

In [6]:
reverse('abuawaish')

h
s
i
a
w
a
u
b
a


---
- We created a function called as `reverse` with one parameter `name` which is type of string and it return nothing that's why this
function has return type is `None`
- Now in function call we simply pass a string as a actual argument
- After calling a function control goes inside the function body and execute the given statements
- In for loop we iterate the `name` variable which is type of string 
- Using slicing we iterates the string in reverse order 
- And at the end we simply print the string of character one by one.
---

### Q4 Develop a program that finds the factorial of a given number using a `for` loop

In [7]:
def factorial(number: int , fact: int = 1) -> int:
    for i in range(1,number+1):
        fact = fact*i
    return fact

In [8]:
print(factorial(5))

120


---
- we define a function name as factorial and passes two parameter, first one is number which is type of interger and second one is fact
which is type of integer has a default value is set to 1.
- After function call control goes inside the body of the function and execute the statements
- In for loop, iterate the number from 1(included) to n+1(excluded)
- Inside the for loop we simply multiply the fact with each individual number and assign it to in `fact` variable
- Finally we return the result and print it...
---

### Q5 Create a program to print the multiplication table of a given number using a `for` loop.


In [9]:
def table(n: int) -> None:
    for i in range(1,11):
        print(f'{n} * {i} : {n*i}')

In [10]:
table(2)

2 * 1 : 2
2 * 2 : 4
2 * 3 : 6
2 * 4 : 8
2 * 5 : 10
2 * 6 : 12
2 * 7 : 14
2 * 8 : 16
2 * 9 : 18
2 * 10 : 20


---
- Here we create a function called as table which basically print the multiplication table of given number `n`
- At function call we pass a actual argument after that at fuction defination `n` is a formal argument which holds the some value
- In for loop , we select a range from 1(included) to 11(excluded)
- Inside the for loop we simply print the value of `n` , `i` and multiplication of `n*i`
- Finally control goes terminated after completion of task
---

### Q6 Write a program that counts the number of even and odd numbers in a list using a `for` loop.

In [11]:
def count_number(number: list[int]) -> None:
    count_even = 0
    count_odd = 0
    for i in number:
        if i%2 == 0:
            count_even+=1
        else:
            count_odd+=1
   
    print(f'There are total {count_even} even number are found')
    print(f'There are total {count_odd} odd number are found')

In [12]:
numbers = [1,2,3,4,5,6,7,8,9]
count_number(numbers)

There are total 4 even number are found
There are total 5 odd number are found


---
- We have a function name as count_number which takes `number` as a parameter which is type of list of interger
- After function call control goes inside the function body and executes the statement
- In for loop, we iterate the list of interger and check if number has remainder 0 then we simply increment the counter by 1 i.e. `count_even = count_even + 1`
- Else if number has remainder not to 0 i.e. 1 then we increment the counter by 1 i.e. `count_odd = count_odd + 1`
- And finally we print the result.
---

### Q7 Develop a program that prints the squares of numbers from 1 to 5 using a `for` loop.

In [13]:
def square(n: int) -> None:
    for i in range(1,n+1):
        print(f'square of {i} is : {i**2}')

In [14]:
n = 5
square(n)

square of 1 is : 1
square of 2 is : 4
square of 3 is : 9
square of 4 is : 16
square of 5 is : 25


---
- We have created a function name as square which takes single argument
- Now at function call we pass `n` as actual argument
- Then control goes inside the function body and execute the statements
- In for loop, we iterate `n` from 1 to 5
- After that every iteration we simply print the square of each number which is ranging from 1 to 5 with the help of `double asterisk operator`.
- After the completion of task the control goes terminated.
---

### Q8 Create a program to find the length of a string without using the `len()` function

In [15]:
def find_length(name: str) -> int:
    count = 0
    for i in name:
        count+=1
    return count

In [16]:
find_length('abuawaish7')

10

---
- We have a function called as find_length which is user define and it takes only one parameter
- After function call the variable `name` holds the string `abuawaish7`
- Set count is equal to zero
- In for loop, iterate the name variable character by character
- Inside for loop we simply increment the counter by 1 till last character
- Finally we return the count and print it.
---

### Q9 Write a program that calculates the average of a list of numbers using a `for` loop.

In [17]:
def average(number: list[int]) -> int:
    sum = 0
    for i in number:
        sum = sum+i
    avg = sum/len(number)
    return avg

In [18]:
print(average([2,3,4,5]))

3.5


---
- We define a function called as average and it takes one parameter i.e. `number` which is type of list of integer
- After function call, control goes inside the function body and executes the statements
- The sum variable initialize with zero
- In for loop, we iterate the list
- Inside the for loop, Each number of list is added with `sum` variable and assign to the `sum` variable
- After adding all numbers of list we simply divide it by 2 in order to get the average of the list of numbers and assign it to in `avg` variable
- Finally we return average of a list of numbers
---

### Q10 Develop a program that prints the first `n` Fibonacci numbers using a `for` loop.

In [19]:
def  fibonacci_series(n: int) -> None:
    f1 = 0
    f2 = 1
    print(f1,end=" ")
    for i in range(1,n+1):
        print(f2,end=" ")
        next = f1+f2
        f1 = f2
        f2 = next

In [20]:
n = 10
fibonacci_series(n)

0 1 1 2 3 5 8 13 21 34 55 

---
- `def fibonacci_series(n: int) -> None`: - This line defines a function named fibonacci_series that takes an integer n as an argument and doesn't return any value (`hence -> None`).
- `f1 = 0 and f2 = 1` - These variables initialize the first two numbers of the Fibonacci sequence. f1 holds the value 0, and f2 holds the value 1.
- `print(f1,end=" ")` - This prints the first number of the Fibonacci series (f1) with a space at the end.
- `for i in range(1, n+1):` - This for loop is used to generate the remaining numbers in the Fibonacci series from the third number up to the nth number.
- Inside the loop:
- `print(f2, end=" ")` - This prints the current Fibonacci number (f2) with a space at the end.
- `next = f1 + f2` - This calculates the next Fibonacci number by adding the previous two numbers (f1 and f2).
- `f1 = f2 and f2 = next` - These lines update f1 to the value of f2 and f2 to the calculated next value, preparing for the next iteration.
- `n = 10` - This line assigns the value 10 to the variable n.
- `fibonacci_series(n)` - This line calls the fibonacci_series function with the argument n, which will print the Fibonacci series up to the nth term.
---

# Intermediate Level:

### Q11 Write a program to check if a given list contains any duplicates using a `for` loop.

In [21]:
def check_duplicate(number: list[any]) -> str:
    unique = []
    for i in number:
        if i not in unique:
            unique.append(i)
    if len(number) == len(unique):
        return 'duplicate element are not found'
    else:
        return 'duplicate element are found'

In [22]:
list1 = [1,2,3,'a',2.5,'a']
list2 = [6,4,1,'a',4.5,3]
print(check_duplicate(list1))
print(check_duplicate(list2))

duplicate element are found
duplicate element are not found


---
- we have created a called as `check_duplicate` which takes one argument
- Input: `number` (a list containing elements of any type) and return Type: str
- initializes an empty list called unique.
- Iterates through each element i in the input list number.
- Checks if the element i is already present in the unique list.
- If i is not in unique, it appends i to the unique list.
- After the iteration, it compares the length of the original list number with the length of the unique list.
- If the lengths are the same, it means there are no duplicate elements in the original list, and it returns `duplicate elements are not found`. Otherwise, it returns `duplicate elements are found`.
- Finally contol goes terminated
---

###  Q12 Create a program that prints the prime numbers in a given range using a `for` loop.


In [23]:
def print_prime_numbers_within_a_range(start: int,end: int) -> None:
     print(f"Prime numbers between {start} and {end}:")
     for num in range(start, end+1):
        if num > 1:
            is_prime = True
            for i in range(2, num):
                if num % i == 0:
                    is_prime = False
                    break
            if is_prime:
                print(num)

In [24]:
start = int(input(f'enter starting number : '))
end = int(input(f'enter ending number : '))
print_prime_numbers_within_a_range(start,end)

enter starting number :  10
enter ending number :  20


Prime numbers between 10 and 20:
11
13
17
19


---
- The function print_prime_numbers_within_a_range is defined with two parameters `start` and `end`.
- It prints a message indicating the range of numbers it will search for prime numbers
- It uses a for loop to iterate through each number in the range from start to end (inclusive).
- For each number in the range, it checks if the number is greater than 1 (since 1 and numbers less than 1 are not prime).
- If the number is greater than 1, it sets a boolean variable is_prime to `True`.
- It then uses another for loop to check if the number is divisible by any integer between 2 and the number itself (excluding the number). If it is divisible by any number in this range, it sets is_prime to `False` and breaks out of the loop.
- If is_prime remains True after the inner loop completes, it means the number is prime, and it is printed.
- Outside the function definition, the code prompts the user to input the starting and ending numbers for the range of prime numbers they want to find.
- It then calls the `print_prime_numbers_within_a_range` function with the provided starting and ending numbers to find and print the prime numbers within that range.
---

### Q13 Develop a program that counts the number of vowels in a string using a `for` loop.

In [25]:
def count_vowel(string: str) -> int:
    count = 0
    vowels = list('aeiou')
    for char in string:
        if char in vowels:
            count+=1
    return count

In [26]:
string: str = input('enter the string : ')
print(count_vowel(string))

enter the string :  abu awaish


5


---
- Defines a function named count_vowel that takes a string (string) as input and returns an integer (int) representing the count of vowels in the input string.
- `count` is initialized to 0. This variable will be used to keep track of the count of vowels in the string.
- `vowels` is a list containing the characters 'a', 'e', 'i', 'o', and 'u', which are considered vowels.
- In for loop, it iterates through each character (char) in the input string.
- For each character, it checks if the character is present in the vowels list.
- If the character is a vowel (i.e., it exists in the vowels list), the count variable is incremented by 1.
- After counting all the vowels in the input string, the function returns the final count of vowels.
- The input string provided by the user is passed as an argument to the `count_vowel` function.
- Finally, it prints the count of vowels in the entered string.
---


### Q14 Write a program to find the maximum element in a 2D list using a nested `for` loop.

In [27]:
def find_max_2d(input_list: list[int]) -> int:
    if not input_list:
        return None 
    
    max_element = input_list[0][0] 
    
    for row in input_list:
        for elem in row:
            if elem > max_element:
                max_element = elem  
    
    return max_element

In [28]:
my_2d_list = [
    [3, 7, 1],
    [8, 4, 5],
    [2, 9, 6]
]

max_value = find_max_2d(my_2d_list)
print("The maximum element in the 2D list is:", max_value)

The maximum element in the 2D list is: 9


---
- The function `find_max_2d` takes in a 2D list of integers `(input_list)` as its parameter and specifies that it will return an integer.
- The function begins with a check to see if the `input_list` is empty. If it is empty `(not input_list)`, the function returns `None`.
- If the input list is not empty, it initializes `max_element` as the first element of the 2D list `(input_list[0][0])`. This assumes that the list is not empty, as otherwise, an index error would occur.
- The function then iterates through each row in the 2D list using a nested loop. For each element `(elem)` in the row, it compares it with the current `max_element`.
- If the current element `(elem)` is greater than the current `max_element`, max_element is updated to be equal to that element.
- After traversing through all elements in the 2D list, the function returns the `max_element`, which holds the maximum value found in the entire 2D list.
- Lastly, outside the function definition, there is a sample 2D list `my_2d_list` provided, which contains integer values. The function `find_max_2d` is called with this list, and the maximum value returned by the function is stored in `max_value`. Finally, the code prints the message along with the maximum value found in the 2D list.
---

### Q15 Create a program that removes all occurrences of a specific element from a list using a `for` loop.

In [29]:
def removes_all_occurrences(number: list[int] , element_to_remove: int) -> list[int]:
    new_list = []
    for i in number:
        if element_to_remove != i:
            new_list.append(i)
    return new_list

In [30]:
number = [2,3,4,5,5,6,7]
element_to_remove = int(input('enter the element is to be remove from the given list : '))
print(f'Before removes all occurrences of a specific element from a list')
print(number)
print(f'After removes all occurrences of a specific element from a list')
print(removes_all_occurrences(number,element_to_remove))

enter the element is to be remove from the given list :  5


Before removes all occurrences of a specific element from a list
[2, 3, 4, 5, 5, 6, 7]
After removes all occurrences of a specific element from a list
[2, 3, 4, 6, 7]


---
- `removes_all_occurrences` this function takes in two parameters `number` A list of integers, `element_to_remove` An integer that represents the element to be removed from the list
- Inside the function:
It initializes an empty list `new_list`.
Iterates through each element i in the number list.
Checks if the `element_to_remove` is not equal to the current element `i`. If they are not equal, it appends the element `i` to the `new_list`.
Returns the `new_list` containing elements from number except those that match the `element_to_remove`
- Main Execution:
The code then initializes a list number with some integers `[2, 3, 4, 5, 5, 6, 7]`.
It prompts the user to input an integer value `element_to_remove`, which specifies the element to be removed from the list.
It prints the original list `(number)` before the removal of the specified element.
It calls the `removes_all_occurrences` function, passing the `number` list and the `element_to_remove` as arguments.
Finally, it prints the modified list returned by the `removes_all_occurrences` function, which does not contain occurrences of the specified element.
---

### Q16 Develop a program that generates a multiplication table for numbers from 1 to 5 using a nested `for` loop.

In [31]:
def  multiplication_table(start: int = 1 , end: int = 5) -> None:
    for i in range(start,end+1):
        print(f'multiplication_table for {i} ↓')
        print()
        for j in range(1,11):
            print(f'{i}*{j} : {i*j}')
        print()

In [32]:
multiplication_table()

multiplication_table for 1 ↓

1*1 : 1
1*2 : 2
1*3 : 3
1*4 : 4
1*5 : 5
1*6 : 6
1*7 : 7
1*8 : 8
1*9 : 9
1*10 : 10

multiplication_table for 2 ↓

2*1 : 2
2*2 : 4
2*3 : 6
2*4 : 8
2*5 : 10
2*6 : 12
2*7 : 14
2*8 : 16
2*9 : 18
2*10 : 20

multiplication_table for 3 ↓

3*1 : 3
3*2 : 6
3*3 : 9
3*4 : 12
3*5 : 15
3*6 : 18
3*7 : 21
3*8 : 24
3*9 : 27
3*10 : 30

multiplication_table for 4 ↓

4*1 : 4
4*2 : 8
4*3 : 12
4*4 : 16
4*5 : 20
4*6 : 24
4*7 : 28
4*8 : 32
4*9 : 36
4*10 : 40

multiplication_table for 5 ↓

5*1 : 5
5*2 : 10
5*3 : 15
5*4 : 20
5*5 : 25
5*6 : 30
5*7 : 35
5*8 : 40
5*9 : 45
5*10 : 50



---
- We have created the function named as `multiplication_table` that takes two parameters `(start and end)` with default values start = 1 and end = 5.
This function doesn't return any value `(None is specified in the function annotation -> None)`.
- Inside the function:
- The function starts by looping through each number from start to end (inclusive) using `for i in range(start, end + 1)`.
- For each number i within this range, it prints a header indicating the multiplication table for that specific number using `print(f'multiplication_table for {i} ↓')`.
- After printing the header, it starts a nested loop from 1 to 10 `(for j in range(1, 11))` to generate the multiplication table for the current number i.
- Within the inner loop, it prints each multiplication operation along with its result using the format `print(f'{i}*{j} : {i*j}')`.
- An empty line `(print())` is added after printing the entire multiplication table for a particular number i to enhance readability.
- Function call:
- The function `multiplication_table()` is called without any arguments. Since the parameters start and end have default values (start = 1 and end = 5), it generates multiplication tables for numbers 1 to 5.
---

### Q17 Write a program that converts a list of Fahrenheit temperatures to Celsius using a `for` loop.

In [33]:
def fahrenheit_to_celsius(fahrenheit_temperatures: list[int]) -> list[float]:
    celsius_temperatures = []
    for fahrenheit in fahrenheit_temperatures:
        celsius = (fahrenheit - 32) * 5 / 9
        celsius_temperatures.append(celsius)
    return celsius_temperatures

In [34]:
fahrenheit_list = [32, 68, 86, 104, 122]
print(fahrenheit_to_celsius(fahrenheit_list))

[0.0, 20.0, 30.0, 40.0, 50.0]


---
- The function defined as `fahrenheit_to_celsius` takes one argument which is type of list of interger and return type is a list of float
- After that in function body , we created a variable known as `celsius_temperatures` which is type list and it set to empty
- In for loop, we simply iterate the list using a variable define as `fahrenheit`
- Inside the for loop, we simply convert Fahrenheit to Celsius using this formule `(fahrenheit - 32) * 5 / 9` and assign to it in `celsius` variable
- After that we append the `celsius` in `celsius_temperatures`
- This process is repeat till the last element of the list.
- After successfully conversion, we going to return the new list i.e. `celsius_temperatures` which hold only floating point number and it
indicates the Tempeartures in Celcius
- In function call, We have a list of type integer which indicates Temperatures in Fahrenheit
- Then , it will be pass to the function as Actual Argument.
---

### Q18 Create a program to print the common elements from two lists using a `for` loop.

In [35]:
def print_common_elements(num1: list[int], num2: list[int]) -> list[int]:
    common_elements_list = []
    for i in num1:
        if i in num2:
            common_elements_list.append(i)
    return common_elements_list

In [36]:
num1 = [5,6,7,2,3]
num2 = [1,9,3,5,4]
print(print_common_elements(num1,num2))

[5, 3]


---
- The function `print_common_elements` takes two lists, `num1` and `num2`, as input arguments and initializes an empty list called `common_elements_list` to store the common elements found between the lists.
- It iterates through each element (i) in the `num1` list using a for loop.
- Inside the loop, it checks if the current element (i) from `num1` exists in the `num2` list using the if i in num2 condition.
- If the element i is present in both `num1` and `num2`, it adds that element to the `common_elements_list` using the `common_elements_list.append(i)` statement.
- Finally, the function returns the `common_elements_list` containing the integers that are common in both num1 and num2.
- The code then defines `num1` and `num2` lists and calls the `print_common_elements` function with these lists as arguments. The result of this function call is printed using print()
---

### Q19 Develop a program that prints the pattern of right-angled triangles using a `for` loop. Use ‘*’ to draw the

In [37]:
def print_right_angle_triangle(rows: int) -> None:
    for i in range(1, rows + 1):
        for j in range(1, i + 1):
            print('*', end=' ')
        print()

In [38]:
print_right_angle_triangle(5)

* 
* * 
* * * 
* * * * 
* * * * * 


---
- The function `print_right_angle_triangle` takes the parameter `rows`, which determines the number of rows in the `right-angled` triangle.
- The outer for loop `(for i in range(1, rows + 1))` controls the number of rows in the triangle. It starts from 1 and goes up to rows.
- The inner for loop `(for j in range(1, i + 1))` controls the number of `asterisks(*)` printed in each row. It starts from 1 and goes up to the current row number i.
- `print('*', end=' ')` is used to print an `asterisk(*)` without moving to the next line. `end=' '` ensures that the next print statement will continue on the same line.
- After printing the asterisks for a particular row, `print()` is used to move to the next line for the next row.
- And These all process will continue till the our goal.
---

### Q20 Write a program to find the greatest common divisor (GCD) of two numbers using a `for` loop.

In [39]:
def find_gcd(a: int, b: int) -> int:
    gcd = 1
    minimum = min(a, b)
    for i in range(1, minimum + 1):
        if a % i == 0 and b % i == 0:
            gcd = i  
    return gcd

In [40]:
num1 = 36
num2 = 48
result = find_gcd(num1, num2)
print(f"The GCD of {num1} and {num2} is: {result}")

The GCD of 36 and 48 is: 12


---
- The function `find_gcd` takes two numbers `a` and `b` as input arguments.
- It initializes the `gcd` variable to 1, which is the minimum possible GCD.
- The minimum of the two numbers `a`and `b`is calculated and stored in the `minimum` variable
- The `for` loop iterates through numbers from 1 up to the minimum value.
- Inside the loop, it checks if both `a` and `b` are divisible by the current number (i). If they are both divisible, it updates the `gcd` variable with the current number (i) since it's a common divisor.
- Finally, the function returns the calculated GCD.
---

# Advanced Level:

### Q21 Create a program that calculates the sum of the digits of numbers in a list using a list comprehension.

In [41]:
def digit_sum(number: int) -> int:
    return sum(int(digit) for digit in str(number) if digit.isdigit())

In [42]:
numbers = [123, 456, 789]
sum_of_digits = [digit_sum(num) for num in numbers]
for i in range(len(numbers)):
    print(f"Number: {numbers[i]}, Sum of digits: {sum_of_digits[i]}")

Number: 123, Sum of digits: 6
Number: 456, Sum of digits: 15
Number: 789, Sum of digits: 24


---
- `digit_sum` This function takes a parameter `number`.
- It converts the number into a string using `str(number)`
- It iterates through each character (`digit`) in the string using a generator expression.
- For each character, it checks if it's a digit using `isdigit()` method.
- If it's a digit, it converts it back to an integer using `int(digit)`.
- Finally, it returns the sum of all these individual digits.
- List `numbers`,It's a list containing three integer values: 123, 456, and 789.
- List comprehension `sum_of_digits`, It creates a new list called `sum_of_digits`
- For each number in the numbers list, it calculates the sum of its digits using the `digit_sum` function defined earlier.
- The resulting list `sum_of_digits` will contain the sum of digits for each number in the numbers list.
- In for loop, It iterates through the indices of the numbers list using `range(len(numbers))`.
- For each index `i`, It prints the original number from the numbers list at index `i`.
- It prints the sum of digits for that number from the `sum_of_digits` list at the same index `i`.
---

### Q22 Write a program to find the prime factors of a given number using a `for` loop and list comprehension.

In [43]:
def prime_factors(n: int) -> list[int]:
    factors = [div for div in range(2, n+1) if n % div == 0]

    prime_factors = []
    for factor in factors:
        is_prime = True
        for divisor in range(2, factor):
            if factor % divisor == 0:
                is_prime = False
                break
        if is_prime:
            prime_factors.append(factor)

    return prime_factors

In [44]:
number = int(input("Enter a number: "))
result = prime_factors(number)
print(f"Prime factors of {number} are: {result}")

Enter a number:  12


Prime factors of 12 are: [2, 3]


---
- There is a function name as `prime_factors` which takes one argument 'n' and it return list of integer value which
indicates the prime factors of given number.
- Inside the function there is a `factors` variable (type list) and it is responsible for storing all possible values which is divisible `n` by the
value ranging from 2 to n+1 with help of `list comprehension`
- After that we create an empty list which is capable for storing the `prime factors` for given number
- In outer `for` loop, we simply iterate over the `factors` list 
- inside the outer `for` loop, there is an `is_prime` varible which is set to `True` first
- Now inner `for` loop it start from 2 and end with factor-1
- inside the inner `for` loop, if statement checks the condition `factor % divisor == 0:` if it is True then the `is_prime` variable is set to be `False`
- After that we jump out of the inner loop using break statement
- The if statement which is inside the outer `for` loop is reponsible for checking the `is_prime` is True. Then it append the `factor` in ` prime_factors` list
- Finally we return the prime factors of given number which is type list of interger
---

### Q23 Develop a program that extracts unique elements from a list and stores them in a new list using a list comprehension.

In [45]:
def store_unique(number: list[int]) -> list[int]:
    unique = []
    [unique.append(el) for el in number if el not in unique]
    return unique

In [46]:
num = [12,34,56,12,45,1,2,1,2,6]
print(store_unique(num))

[12, 34, 56, 45, 1, 2, 6]


---
- We have a function a name as `store_unique` which take one argument `number` as list of integer and it return list of integer back. 
- Inside the function defination we initialize the variable `unique` as list which holds only distinct elements.
- using list comprehension the unique elements are extracted and store in the list called as `unique`
- Inside the list comprehension, If statement check the element from list `number` are not present in list `unique` (`if el not in unique`)
- With this `unique.append(el)` statement we are appending those element which are unique only.
- Finally the function `store_unique` returns the list `unique`
- We create an variable called as `num` which are type of list of integer and it containing the duplicates values as well
- At function call, we simply the print the result on the terminal.
---

### Q24 Create a program that generates a list of all palindromic numbers up to a specified limit using a list comprehension.

In [47]:
def is_palindrome(num: str) -> bool:
    return str(num) == str(num)[::-1]

def generate_palindromes(limit: int) -> list[int]:
    return [num for num in range(limit + 1) if is_palindrome(num)]


In [48]:
limit = int(input("Enter the limit for palindromic numbers: "))
palindromes = generate_palindromes(limit)
print(f"Palindromic numbers up to {limit}:")
print(palindromes)

Enter the limit for palindromic numbers:  121


Palindromic numbers up to 121:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33, 44, 55, 66, 77, 88, 99, 101, 111, 121]


---
- `is_palindrome()` ,This function takes a number (`num`) as input and checks if it's a palindrome and it return the boolean value.
- `str(num)` converts the number to a string.
- `str(num)[::-1]` reverses the string representation of the number using Python's slicing (`[::-1]`).
- It returns `True` if the original number is equal to its reversed version (`i.e., if it's a palindrome`), otherwise, it returns `False`.
- `generate_palindromes()`, This function generates a list of palindromic numbers up to a specified limit.
- It takes a parameter `limit`, which represents the upper limit until which palindromic numbers need to be generated and it return the
list of integer values which contains only palindromic numbers upto specified limit.
- Inside this function, a list comprehension is used:
- `range(limit + 1)` generates numbers from 0 up to limit
- For each number in this range, it checks if it's a palindrome using the `is_palindrome()` function.
- Numbers that satisfy the palindrome condition are included in the resulting list.
- Taking user input:
`limit = int(input("Enter the limit for palindromic numbers: "))`: This line prompts the user to input the limit for generating palindromic numbers and converts the input to an integer (int() function).
- Generating and displaying palindromic numbers:
`palindromes = generate_palindromes(limit)`: Calls the `generate_palindromes()` function with the user-inputted limit and stores the list of palindromic numbers in the variable palindromes.
- `print(f"Palindromic numbers up to {limit}:")`: Prints a message indicating the limit provided by the user.
- `print(palindromes)`: Prints the list of palindromic numbers generated within the specified limit.
---

### Q25 Write a program to flatten a nested list using list comprehension

In [49]:
def flatten_list(my_list: list[int]) -> list[int]:
    flat_list = [num for sublist in my_list for num in sublist]
    return flat_list

In [50]:
nested_list = [[1], [2, 3], [4, 5, 6, 7]]
result = flatten_list(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7]


---
-  We have created a function name as `flatten_list` which takes only single parameter `my_list` which is type list of integer
and it returns a list of integer values of single dimensional list.
- `flat_list = [num for sublist in my_list for num in sublist]`:
This line uses a list comprehension to iterate through each sublist (`sublist`) in the input `my_list`.
- For each `sublist`, it iterates through each num in that sublist and appends it to the `flat_list`
- After that it returns the `flat_list` that contains all the integers from the nested list after flattening.
- `nested_list = [[1], [2, 3], [4, 5, 6, 7]]`:
This is a sample nested list containing three `sublists`, each with different numbers of integers.
- `result = flatten_list(nested_list)`:
Calls the flatten_list function with nested_list as an argument to flatten it.
- `print(result)`:
Prints the result obtained after flattening the `nested_list`.
----

### Q26 Develop a program that computes the sum of even and odd numbers in a list separately using list

In [51]:
def sum_of_even_n_odd(num: list[int]) -> int:
    sum_even = 0
    sum_odd = 0
    for i in num:
        if i % 2 == 0:
            sum_even+=i
        else:
            sum_odd+=i
    return sum_even , sum_odd

In [52]:
def user_input() -> None:
    size = int(input('enter the size of the list : '))
    my_list = []
    for i in range(size):
        el = int(input('enter the element at {} index : '.format(i)))
        my_list.append(el)
    even , odd = sum_of_even_n_odd(my_list)
    print(f'Original list are : {my_list}')
    print(f'Sum of even numbers are : {even}')
    print(f'Sum of odd numbers are : {odd}')

In [53]:
user_input()

enter the size of the list :  5
enter the element at 0 index :  1
enter the element at 1 index :  2
enter the element at 2 index :  3
enter the element at 3 index :  4
enter the element at 4 index :  5


Original list are : [1, 2, 3, 4, 5]
Sum of even numbers are : 6
Sum of odd numbers are : 9


---
- 1. `sum_of_even_n_odd(num: list[int]) -> int`:
- This function takes a list of integers `num` as input and calculates the sum of `even` and `odd` numbers separately within that list.
- It initializes two variables, `sum_even` and `sum_odd`, to keep track of the sums of even and odd numbers, respectively.
- It iterates through each element `i` in the input list `num`.
- If the element `i` is even (`i.e., i % 2 == 0`), it adds `i` to `sum_even`. Otherwise, it adds `i` to `sum_odd`.
- Finally, it returns the sums of even and odd numbers as a tuple: (`sum_even`, `sum_odd`)
- 2. `user_input() -> None`:
- This function prompts the user to input the size of the list and then asks the user to input elements for that list.
- It initializes an empty list called `my_list`.
- It asks the user for the size of the list and then iterates `size` times to get elements for the list by asking the user to input each element.
- After obtaining the list of elements, it calls the `sum_of_even_n_odd()` function with `my_list` as an argument to calculate the sum of even and odd numbers.
- It then prints the original list, the sum of even numbers, and the sum of odd numbers.
---

### Q27 Create a program that generates a list of squares of odd numbers between 1 and 10 using list comprehension.

In [54]:
def list_of_squares_of_odd_numbers() -> list[int]:
    odd_squares = [num**2 for num in range(1,11) if num%2 != 0]
    return odd_squares

In [55]:
list_of_squares_of_odd_numbers()

[1, 9, 25, 49, 81]

--- 
- We defined a function as `list_of_squares_of_odd_numbers` which is responsible for generating a list of squares of odd numbers between 1 and 10
which has no argument but it return list of integer values (`i.e.,list of squares of odd numbers between 1 and 10`)
- `range(1, 11)` generates numbers from 1 to 10 (inclusive).
- `x % 2 != 0` filters only the odd numbers from the generated range.
- `x ** 2` calculates the square of each odd number.
- The resulting list `odd_squares` contains squares of odd numbers between 1 and 10.
---

### Q28 Write a program that combines two lists into a dictionary using list comprehension.

In [56]:
def combines_list(keys: list[str] , values: list[int]) -> dict:
    my_dict = {}
    [my_dict.update([(key,value)]) for key,value in zip(keys,values)]
    return my_dict

In [57]:
keys = ['awaish', 'ayan', 'amaan']
values = [1, 2, 3,]
result = combines_list(keys,values)
print(result)

{'awaish': 1, 'ayan': 2, 'amaan': 3}


---
- The `combines_list` function is defined with two parameters: `keys` (a list of strings) and `values` (a list of integers). It is annotated to specify that it takes lists of strings and integers and returns a dictionary.
- Inside the function:
- 1. It uses a list comprehension `[my_dict.update([(key,value)]) for key,value in zip(keys,values)]` to create a dictionary.
- 2. It uses a zip() function to iterate through both keys and values simultaneously.
- 3. For each pair of corresponding elements (a key-value pair) obtained from `zip(keys, values)`, it uses the `update()` method to add the key-value pair to the `my_dict`.
- 4. The `update()` method takes a list of tuples (in this case, a single tuple) and adds or updates the key-value pair(s) in the dictionary.
- Finally, the function returns the `my_dict`, which contains the combined key-value pairs from the keys and values.
- We defined two variables 1.`keys` the type is list of string and 2.`value` the type is list of integer
- We call the function `combines_list` with two parameters `keys` and `value`
- And the function returns is stored in `result` variable
- At the end we print the output using `print()` function
---

### Q29 Develop a program that extracts the vowels from a string and stores them in a list using list comprehension.

In [58]:
def extracts_vowels(string: str) -> list[str]:
    list_of_vowels = list('aeiou')
    vowels = [v for v in string if v in list_of_vowels]
    return vowels

In [59]:
string = 'This is me abu awaish'
extracts_vowels(string)

['i', 'i', 'e', 'a', 'u', 'a', 'a', 'i']

---
- We defines a function named `extracts_vowels` that takes in a single argument `string`, which is expected to be a string. It also specifies that the function will return a list of strings.
- After that we creates a list named `list_of_vowels` containing individual characters 'a', 'e', 'i', 'o', and 'u'. These characters represent the vowels in the English alphabet.
- It uses a list comprehension to iterate through each character (`v`) in the input string (`string`). It checks whether each character is present in the `list_of_vowels` created earlier.
- For every character in the input string that matches any vowel in `list_of_vowels`, it creates a list called vowels containing those vowels.
- And at the end it returns the list of vowels found in the input string based on the conditions specified in the list comprehension.
- `string = 'This is me abu awaish'`:
This line defines a string variable named `string` containing the text `"This is me abu awaish"`.
- `extracts_vowels(string)`:
This line calls the `extracts_vowels` function with the string variable as an argument, which executes the function and returns a list of vowels found in the provided string.
---

### Q30 Create a program that removes all non-numeric characters from a list of strings using list comprehension.

In [60]:
def remove_non_numeric(strings: list[str]) -> list[str]:
    # List comprehension to filter out non-numeric characters from each string
    modify_string = ["".join(char for char in string if char.isdigit()) for string in strings]
    return modify_string

In [61]:
list_of_strings = ['abc123', '45def', '6ghi78', '9jkl']
# Remove non-numeric characters from the list of strings
result = remove_non_numeric(list_of_strings)
# Print the original list and the cleaned list
print("Original List of Strings:", list_of_strings)
print("List after removing non-numeric characters:", result)

Original List of Strings: ['abc123', '45def', '6ghi78', '9jkl']
List after removing non-numeric characters: ['123', '45', '678', '9']


---
- We created a function named as `remove_non_numeric` which takes only single parameter `strings` which is type of list of string and it returns
list of string which contains only numeric values
- After that we use list comprehension `["".join(char for char in string if char.isdigit()) for string in strings]`
- For loop iterates over the list echa element one by one `for string in strings`
- Using join() function we join those characters together which is type of numeric using for loop  `for char in string if char.isdigit())`
- After getting all numeric characters we return the list of string `modify_string`
- We declare the variable named as `list_of_string` which contains alpha_numeric values
- And return result is store in `result` variable
- Finally we print original list and List after removing non-numeric characters
---

# Challenge Level:

### Q31 Write a program to generate a list of prime numbers using the Sieve of Eratosthenes algorithm and list comprehension.

In [62]:
def sieve_of_eratosthenes(n: int) -> list[int]:
    sieve = [True] * (n + 1)
    sieve[0:2] = [False, False]
    for i in range(2, int(n**0.5) + 1):
        if sieve[i]:
            sieve[i*i:n+1:i] = [False] * len(sieve[i*i:n+1:i])
    return [i for i in range(n + 1) if sieve[i]]

In [63]:
# Example usage
n = 100  # Generate primes up to n
prime_numbers = sieve_of_eratosthenes(n)
print(prime_numbers)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


---
- We define a function `sieve_of_eratosthenes` that takes an integer `n` as input.
- We initialize a boolean list `sieve` of length `n + 1`, where `sieve[i]` indicates if `i` is a prime number.
- We iterate through the numbers up to the square root of `n` and update the sieve list based on the Sieve of Eratosthenes algorithm.
- Finally, we use list comprehension to generate a list of prime numbers by filtering out non-prime numbers from the sieve list.
- We then use the `sieve_of_eratosthenes` function to generate prime numbers up to the specified limit `n` and print the result.
---

### Q32 Create a program that generates a list of all Pythagorean triplets up to a specified limit using list comprehension

In [64]:
def generate_pythagorean_triplets(limit: int) -> list[tuple]:
    triplets = [(a, b, c) for a in range(1, limit)
                          for b in range(a, limit)
                          for c in range(b, limit)
                          if a * a + b * b == c * c]
    return triplets

In [65]:
limit = 20
pythagorean_triplets = generate_pythagorean_triplets(limit)
print(pythagorean_triplets)

[(3, 4, 5), (5, 12, 13), (6, 8, 10), (8, 15, 17), (9, 12, 15)]


---
- `generate_pythagorean_triplets` function: It takes one parameter `limit` which represents the maximum value for the Pythagorean triplets to be generated.
- Three nested for loops are used to iterate through all combinations of `'a'`, `'b'`, and `'c'` values within the given limit.
- `a` starts from 1 and goes up to limit - 1.
- `b` starts from the current `a` value and goes up to limit - 1.
- `c` starts from the current `b` value and goes up to limit - 1.
- Inside the loops, there's an if condition that checks whether the current combination of `'a'`, `'b'`, and `'c'` values satisfies the Pythagorean theorem: `a^2 + b^2 = c^2`.
- If the condition is met, a tuple `(a, b, c)` representing the Pythagorean triplet is appended to the `triplets` list
- The function returns the list of Pythagorean triplets generated within the specified limit.
- The main code then sets the `limit` to 20 and calls the function `generate_pythagorean_triplets` with this limit.
- Finally, it prints out the generated Pythagorean triplets.
---

### Q33 Develop a program that generates a list of all possible combinations of two lists using list comprehension.

In [66]:
def combinations_of_two_list(list1: list[int] , list2: list[str]) -> list[tuple]:
    conbinations = [(x, y) for x in list1 for y in list2]
    return conbinations

In [67]:
list1 = [1,2,3,4,5]
list2 = ['a','b','c','d','e']
result = combinations_of_two_list(list1,list2)
print(result)

[(1, 'a'), (1, 'b'), (1, 'c'), (1, 'd'), (1, 'e'), (2, 'a'), (2, 'b'), (2, 'c'), (2, 'd'), (2, 'e'), (3, 'a'), (3, 'b'), (3, 'c'), (3, 'd'), (3, 'e'), (4, 'a'), (4, 'b'), (4, 'c'), (4, 'd'), (4, 'e'), (5, 'a'), (5, 'b'), (5, 'c'), (5, 'd'), (5, 'e')]


---
- We define the function named as `combinations_of_two_list` which takes two parameters `list1` which is expected to be a list containing integers, and `list2` which is expected to be a list containing strings.
- It specifies that the function will return a list containing tuples.
- `combinations = [(x, y) for x in list1 for y in list2]` this line uses a list comprehension to generate combinations
- For each element `x` in `list1` and for each element `y` in `list2`, it creates a `tuple (x, y)` and adds it to the `combinations` list.
- This process results in combinations of elements from `list1` paired with elements from `list2`.
- The function returns the list `combinations`, which contains tuples representing the combinations of elements from `list1` and `list2`.
- outside the function : 
- Here, list1 is assigned `[1, 2, 3, 4, 5]`, and list2 is assigned `['a', 'b', 'c', 'd', 'e']`.
- The function `combinations_of_two_list` is called with `list1` and `list2` as arguments, and the result is stored in the variable `result`.
- Finally, the `result`, which contains all the combinations of elements from `list1` and `list2` as tuples, is printed to the console.
---

### Q34 Write a program that calculates the mean, median, and mode of a list of numbers using list comprehension. 

In [68]:
class measures_of_central_tendency :
    def __init__(self,num: list[int]) -> None:
        self.number = num 
        
    def mean_calculate(self) -> float:
        mean = sum([x for x in self.number]) / len(self.number)
        return mean
        
    def median_calculate(self) -> float:
        sorted_list = sorted(self.number)
        length = len(sorted_list)

        median = (sorted_list[length // 2] if length % 2 != 0 else
              (sorted_list[length // 2 - 1] + sorted_list[length // 2]) / 2)
        return median

    def mode_calculate(self) -> int:
        mode = max(set([x for x in self.number if self.number.count(x) == max([self.number.count(i) for i in self.number])]), key=self.number.count)
        return mode

In [69]:
obj = measures_of_central_tendency([1,2,3,4,5,5])

In [70]:
obj.mean_calculate()

3.3333333333333335

In [71]:
obj.median_calculate()

3.5

In [72]:
obj.mode_calculate()

5

---
- `class measures_of_central_tendency` : This line declares a class named `measures_of_central_tendency`.
- `def __init__(self, num: list[int]) -> None` : This method is the class constructor, initializing an instance of the class. It takes a parameter `num`, which is expected to be a list of integers `(list[int])`. This list is stored as an attribute named number within the class instance.
Note : A constructor does not return any value.
- `def mean_calculate(self) -> float` : The 1mean_calculate `method calculates` the mean of the list by summing all the numbers in the list and then dividing by the total count of numbers. It returns the calculated mean as a floating-point number.
- `def median_calculate(self) -> float` : The 1median_calculate1 method first sorts the list of numbers in ascending order. It then calculates the median based on whether the total count of numbers is `odd` or `even`. The median value is returned as a floating-point number.
- `def mode_calculate(self) -> int` : The `mode_calculate` method uses a list comprehension and the `max` function to find the mode of the list. It constructs a set of elements with maximum occurrences and then finds the element with the highest count. The mode is returned as an integer.
---

### Q35 Create a program that generates Pascal's triangle up to a specified number of rows using list comprehension.

In [73]:
def generate_pascals_triangle(rows: int) -> list[list[int]]:
    triangle = [[1] * (row + 1) for row in range(rows)]
    
    for row in range(2, rows):
        for col in range(1, row):
            triangle[row][col] = triangle[row - 1][col - 1] + triangle[row - 1][col]
    
    return triangle

def print_pascals_triangle(triangle: list[list[int]]):
    for row in triangle:
        print(" ".join(map(str, row)))

In [74]:
num_of_rows = 5
pascals_triangle = generate_pascals_triangle(num_of_rows)
print_pascals_triangle(pascals_triangle)

1
1 1
1 2 1
1 3 3 1
1 4 6 4 1


---
- `generate_pascals_triangle` : This function takes an integer `rows` as input and generates Pascal's Triangle up to the specified number of rows. It uses a nested list comprehension to initialize a 2D list (`triangle`) with each element initialized to 1. The size of each row is determined by the row index (`row + 1`).
- Then, a nested loop is used to calculate the values inside the triangle. The outer loop iterates over each row starting from the third row (index 2), and the inner loop iterates over the columns within each row (excluding the first and last elements). The values are calculated using the combination formula: `C(n, k) = C(n-1, k-1) + C(n-1, k)`. The calculated values are updated in the `triangle` list.
- Finally, the generated Pascal's Triangle is returned.
- `print_pascals_triangle` : This function takes the generated Pascal's Triangle (`triangle`) as input and prints it row by row. The for loop iterates over each row, and `map(str, row)` is used to convert each integer in the row to a string. `join` is then used to concatenate these strings with spaces between them, creating a formatted row. The `print` statement prints each row on a new line.
- To use these functions, you can call `generate_pascals_triangle` to generate the triangle and then pass the result to `print_pascals_triangle` to print it.
---

### Q36 Develop a program that calculates the sum of the digits of a factorial of numbers from 1 to 5 using list comprehension.

In [75]:
def fact(i: int) -> int:
    if i==1:
        return 1
    else:
        return i*fact(i-1)

def sum_of_digits(n: int) -> int:
    return sum(int(i) for i in str(n))

In [76]:
factorial = [fact(i) for i in range(1,6)]
print(factorial)
result = [sum_of_digits(fact(i)) for i in range(1,6)]
print(result)

[1, 2, 6, 24, 120]
[1, 2, 6, 6, 3]


---
- The `fact` function is a recursive function that calculates the factorial of a given number `i`. It checks if the input `i` is equal to 1, in which case it returns 1. If `i` is not 1, it calculates `i` multiplied by the factorial of `i-1`.
- The `sum_of_digits` function takes a number `n` as input and returns the sum of its digits. It achieves this by converting the number to a string, iterating through the digits, converting them back to integers, and finally summing them up using a list comprehension.
- The script then creates a list called `factorial` by applying the `fact` function to the numbers 1 through 5 using a list comprehension.
- Similarly, it creates another list called `result` by applying the `sum_of_digits` function to the factorials calculated in the previous step, again using a list comprehension.
- Finally, the script prints both the `factorial` and `result` lists to the console.
---

### Q37 Write a program that finds the longest word in a sentence using list comprehension.

In [77]:
def finds_the_longest_word(sentence: str) -> str:
    longest_word = [word for word in sentence.split() if len(word) == len(max(sentence.split(),key=len))][0]
    return longest_word

In [78]:
sen = input('Enter the sentence you want : ')
result = finds_the_longest_word(sen)
print(f'The longest word in the given sentence is : {result}')

Enter the sentence you want :  earth revolves around the sun


The longest word in the given sentence is : revolves


---
- The function `finds_the_longest_word` takes a single parameter sentence, which is expected to be a string.
- Inside the function:
  1. `sentence.split()` splits the input sentence into a list of words based on whitespace.
  2. `max(sentence.split(), key=len)` finds the word with the maximum length in the list of words obtained from the split sentence. The `key=len` argument specifies that the length of each word should be considered for finding the maximum.
  3. `[word for word in sentence.split() if len(word) == len(max(sentence.split(),key=len))]` is a list comprehension that filters the words from the split sentence, keeping only those words whose length is equal to the length of the longest word in the sentence.
  4. `[0]` at the end of the list comprehension selects the first word from the filtered list of words, which is the longest word.
  5. `longest_word` variable stores the longest word found.
- The function returns the `longest_word`.
- Outside the function:
  1. `input('Enter the sentence you want : ')` prompts the user to input a sentence.
  2. The input sentence is passed to the `finds_the_longest_word` function.
  3. The result returned by the function is stored in the variable `result`.
  4. Finally, a formatted string is printed to display the longest word found in the input sentence.
---

### Q38 Create a program that filters a list of strings to include only those with more than three vowels using list comprehension.

In [3]:
def count_vowels(word: str) -> int:
    vowels = list("aeiouAEIOU")
    return sum(1 for char in word if char in vowels)

def filter_strings_with_more_than_three_vowels(string_list: list[str]) -> str:
    return [word for word in string_list if count_vowels(word) > 3][0]


In [4]:
input_list = ["Awaish", "Ayan", "Serazi", "Salik", "ShayanAli"]
filtered_list = filter_strings_with_more_than_three_vowels(input_list)
print(filtered_list)

ShayanAli


---
- This function,`count_vowels`, takes a string `word` as input and returns the count of vowels in that word. It initializes a list of vowels containing both lowercase and uppercase vowels. Then, it uses a generator expression within the sum function to count the occurrences of vowels in the word.
- This function,`filter_strings_with_more_than_three_vowels`,takes a list of strings `string_list` as input and returns the first string from the list that has more than three vowels. It uses a list comprehension to iterate through each word in the input list and filters out the words for which the count of vowels is greater than 3. Then, it returns the first word from the filtered list using indexing `[0]`.
- Before function call : creates an input list of strings `input_list`
- At function call : the `filter_strings_with_more_than_three_vowels` function with `input_list` as input to get the filtered list.
- After function call : Finally, it prints the first string from the filtered list.
---

### Q39 Develop a program that calculates the sum of the digits of numbers from 1 to 1000 using list comprehension.

In [19]:
def  sum_of_the_digits(start : int = 1 , end : int = 1000) -> list[int]:
    SumOfDigits = [sum(int(c) for c in str(i)) for i in range(start,end+1)]
    return SumOfDigits

In [21]:
result = sum_of_the_digits()
print(result)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 10, 11, 12, 13, 14

---
- We defines a function named `sum_of_the_digits` that takes two parameters `start` and `end`, both of which have default values of `1` and `1000` respectively. The function returns a list of integers.
- After that we creates a list comprehension. It iterates through each number in the range from `start` to `end`, inclusive. For each number `i`, it converts the number to a string `str(i)`, iterates through each character `c` in that string, converts it back to an integer `int(c)`, and then calculates the sum of these integers using the `sum` function. So, essentially, it calculates the sum of the digits of each number in the range.
- And it returns the list `SumOfDigits` containing the sums of digits for each number in the range specified.
- the 1sum_of_the_digits1 function without providing any arguments, so it will use the default values for `start` and `end`. It assigns the returned list to the variable `result`
- Finally we prints the `result`, which is the list of sums of digits for each number in the range from 1 to 1000.
---

### Q40 Write a program that generates a list of prime palindromic numbers using list comprehension.

In [3]:
def is_prime(n):
    if n < 2:
        return False
    else:
        for i in range(2, n):
            if n % i == 0:
                return False
        else:
            return True

def is_palindrome(n):
    return str(n) == str(n)[::-1]

In [4]:
prime_palindromes = [num for num in range(2, 1000) if is_prime(num) and is_palindrome(num)]

print(prime_palindromes)

[2, 3, 5, 7, 11, 101, 131, 151, 181, 191, 313, 353, 373, 383, 727, 757, 787, 797, 919, 929]


---
- `is_prime Function`:
   1. This function takes a number `n` and checks if it is a prime number.
   2. It first checks if the number is less than 2, in which case it returns `False` because prime numbers are defined as natural numbers greater than 1
  3. In for loop, it iterates through a range from 2 to n-1 and checks if the number is divisible by any of these values `(i.e. i)`. If it is, it returns `False`, as it means the number is not prime.
  4. If the loop completes without finding a divisor, the function returns `True`, indicating that the number is prime
- `is_palindrome Function`:
  1. This function takes a number `n` and checks if it is a palindrome.
  2. It converts the number to a string and then compares the string to its reverse. If they are the same, the number is a palindrome and the function returns `True`otherwise, it returns `False`.
- `prime_palindromes List Comprehension`:
  1. This line uses list comprehension to populate a list called `prime_palindromes` with numbers that satisfy two conditions: being prime and being a palindrome.
  2. It iterates through numbers from 2 to 999 and includes them in the list if both `is_prime(num)` and `is_palindrome(num)` return `True`.
- Finally, the code prints the list `prime_palindromes`, which contains all the prime palindrome numbers between 2 and 999.
---